### ISSUE TITLE
[5.x] missing const correction

### ISSUE THREAD

**Issue by dakyskye** [pawn-lang/YSI-Includes#380]
```c
#include	<YSI_Players\y_text>
#include	<YSI_Coding\y_hooks>

new
	Language:gLangEN,
	Language:gLangGE,
	Language:gLangRU
;

loadtext localization[all];

hook OnScriptInit() {
	gLangEN = Langs_Add("EN", "English");
	gLangGE = Langs_Add("GE", "Georgian");
	gLangRU = Langs_Add("RU", "Russian");
		
	return Y_HOOKS_CONTINUE_RETURN_1;
}
```
got:
```
YSI-Includes\YSI_Coding\y_malloc\y_malloc_warning.inc:8 (warning) user warning: Heap allocation is VERY unst
able.  Use `YSI_NO_HEAP_MALLOC` to disable it, or `YSI_YES_HEAP_MALLOC` to disable this warning.
YSI-Includes\YSI_Players\y_text\y_text_impl.inc:335 (warning) function "Jagged_UnsafeResizeOne" should return a value
YSI-Includes\YSI_Players\y_text\y_text_impl.inc:358 (warning) function "Jagged_UnsafeResizeOne" should return a value
YSI-Includes\YSI_Players\y_text\y_text_impl.inc:369 (warning) function "Jagged_UnsafeResizeOne" should return a value
YSI-Includes\YSI_Players\y_text\y_text_impl.inc:398 (warning) function "Jagged_UnsafeResizeOne" should return a value
YSI-Includes\YSI_Players\y_text\y_text_impl.inc:409 (warning) function "Jagged_UnsafeResizeOne" should return a value
YSI-Includes\YSI_Players\y_text\y_text_impl.inc:570 (warning) symbol is never used: "str"
YSI-Includes\YSI_Players\y_text\y_text_impl.inc:570 (warning) symbol is never used: "file"
YSI-Includes\YSI_Players\y_text\y_text_impl.inc:592 (warning) symbol is never used: "name"
 (warning) literal array/string passed to a non-const parameter
 (warning) literal array/string passed to a non-const parameter
 (warning) literal array/string passed to a non-const parameter
 (warning) literal array/string passed to a non-const parameter
 (warning) literal array/string passed to a non-const parameter
 (warning) literal array/string passed to a non-const parameter
```
The last six warnings are from that lines:
```c
	gLangEN = Langs_Add("EN", "English");
	gLangGE = Langs_Add("GE", "Georgian");
	gLangRU = Langs_Add("RU", "Russian");
```

¯\_(ツ)_/¯

**Comment by Y-Less** [comment]
Fixed.  thanks.

**Comment by samp-pinch** [comment]
@Y-Less I do not think you fixed/merged or whatsoever, i still get same shit

**Comment by Y-Less** [comment]
On 5.x?
